/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getSelector <em>Selector</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getButton <em>Button</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getRadio <em>Radio</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Selector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_Selector()
   * @model containment="true"
   * @generated
   */
  EList<Selector> getSelector();

  /**
   * Returns the value of the '<em><b>Button</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Button}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Button</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_Button()
   * @model containment="true"
   * @generated
   */
  EList<Button> getButton();

  /**
   * Returns the value of the '<em><b>Radio</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Radio}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Radio</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Radio</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_Radio()
   * @model containment="true"
   * @generated
   */
  EList<Radio> getRadio();

} // Component
