/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MensamodelImpl <em>Mensamodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MensamodelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMensamodel()
   * @generated
   */
  int MENSAMODEL = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENSAMODEL__HEADER = 0;

  /**
   * The feature id for the '<em><b>Sidebar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENSAMODEL__SIDEBAR = 1;

  /**
   * The feature id for the '<em><b>Footer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENSAMODEL__FOOTER = 2;

  /**
   * The feature id for the '<em><b>Menus</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENSAMODEL__MENUS = 3;

  /**
   * The number of structural features of the '<em>Mensamodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENSAMODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.HeaderImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Nav</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__NAV = 2;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SidebarImpl <em>Sidebar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SidebarImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSidebar()
   * @generated
   */
  int SIDEBAR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Radio</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__RADIO = 2;

  /**
   * The feature id for the '<em><b>Checkbox</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__CHECKBOX = 3;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__SELECTOR = 4;

  /**
   * The feature id for the '<em><b>Button</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR__BUTTON = 5;

  /**
   * The number of structural features of the '<em>Sidebar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDEBAR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FooterImpl <em>Footer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FooterImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFooter()
   * @generated
   */
  int FOOTER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOTER__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOTER__LINKS = 2;

  /**
   * The number of structural features of the '<em>Footer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOTER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DescriptionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NAVImpl <em>NAV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NAVImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNAV()
   * @generated
   */
  int NAV = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAV__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAV__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Href</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAV__HREF = 2;

  /**
   * The number of structural features of the '<em>NAV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAV_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RadioImpl <em>Radio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RadioImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRadio()
   * @generated
   */
  int RADIO = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO__TITLE = 1;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO__OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Radio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckboxImpl <em>Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CheckboxImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckbox()
   * @generated
   */
  int CHECKBOX = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__TITLE = 1;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ButtonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TITLE = 1;

  /**
   * The feature id for the '<em><b>Href</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__HREF = 2;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SelectorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__TITLE = 1;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
   * @generated
   */
  int LINK = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__URL = 2;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MenuImpl <em>Menu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MenuImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMenu()
   * @generated
   */
  int MENU = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__NAME = 0;

  /**
   * The feature id for the '<em><b>Meal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__MEAL = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__PRICE = 3;

  /**
   * The feature id for the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__IMAGE = 4;

  /**
   * The number of structural features of the '<em>Menu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Mensamodel <em>Mensamodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mensamodel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mensamodel
   * @generated
   */
  EClass getMensamodel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Mensamodel#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mensamodel#getHeader()
   * @see #getMensamodel()
   * @generated
   */
  EReference getMensamodel_Header();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Mensamodel#getSidebar <em>Sidebar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sidebar</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mensamodel#getSidebar()
   * @see #getMensamodel()
   * @generated
   */
  EReference getMensamodel_Sidebar();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Mensamodel#getFooter <em>Footer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Footer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mensamodel#getFooter()
   * @see #getMensamodel()
   * @generated
   */
  EReference getMensamodel_Footer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Mensamodel#getMenus <em>Menus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menus</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mensamodel#getMenus()
   * @see #getMensamodel()
   * @generated
   */
  EReference getMensamodel_Menus();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see org.xtext.example.mydsl.myDsl.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Header#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Header#getName()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Header#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Header#getDescription()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Header#getNav <em>Nav</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nav</em>'.
   * @see org.xtext.example.mydsl.myDsl.Header#getNav()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_Nav();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Sidebar <em>Sidebar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sidebar</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar
   * @generated
   */
  EClass getSidebar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Sidebar#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getName()
   * @see #getSidebar()
   * @generated
   */
  EAttribute getSidebar_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Sidebar#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getDescription()
   * @see #getSidebar()
   * @generated
   */
  EReference getSidebar_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Sidebar#getRadio <em>Radio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Radio</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getRadio()
   * @see #getSidebar()
   * @generated
   */
  EReference getSidebar_Radio();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Sidebar#getCheckbox <em>Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Checkbox</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getCheckbox()
   * @see #getSidebar()
   * @generated
   */
  EReference getSidebar_Checkbox();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Sidebar#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selector</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getSelector()
   * @see #getSidebar()
   * @generated
   */
  EReference getSidebar_Selector();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Sidebar#getButton <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Button</em>'.
   * @see org.xtext.example.mydsl.myDsl.Sidebar#getButton()
   * @see #getSidebar()
   * @generated
   */
  EReference getSidebar_Button();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Footer <em>Footer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Footer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Footer
   * @generated
   */
  EClass getFooter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Footer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Footer#getName()
   * @see #getFooter()
   * @generated
   */
  EAttribute getFooter_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Footer#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Footer#getDescription()
   * @see #getFooter()
   * @generated
   */
  EReference getFooter_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Footer#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Links</em>'.
   * @see org.xtext.example.mydsl.myDsl.Footer#getLinks()
   * @see #getFooter()
   * @generated
   */
  EReference getFooter_Links();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Description#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Description#getName()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NAV <em>NAV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NAV</em>'.
   * @see org.xtext.example.mydsl.myDsl.NAV
   * @generated
   */
  EClass getNAV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NAV#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.NAV#getName()
   * @see #getNAV()
   * @generated
   */
  EAttribute getNAV_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.NAV#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.NAV#getDescription()
   * @see #getNAV()
   * @generated
   */
  EReference getNAV_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NAV#getHref <em>Href</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Href</em>'.
   * @see org.xtext.example.mydsl.myDsl.NAV#getHref()
   * @see #getNAV()
   * @generated
   */
  EAttribute getNAV_Href();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Radio <em>Radio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Radio</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radio
   * @generated
   */
  EClass getRadio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Radio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radio#getName()
   * @see #getRadio()
   * @generated
   */
  EAttribute getRadio_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Radio#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radio#getTitle()
   * @see #getRadio()
   * @generated
   */
  EReference getRadio_Title();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Radio#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radio#getOptions()
   * @see #getRadio()
   * @generated
   */
  EAttribute getRadio_Options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Checkbox <em>Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox
   * @generated
   */
  EClass getCheckbox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Checkbox#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getName()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Checkbox#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getTitle()
   * @see #getCheckbox()
   * @generated
   */
  EReference getCheckbox_Title();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Checkbox#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getOptions()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Button#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getName()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Button#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getTitle()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Title();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Button#getHref <em>Href</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Href</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getHref()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Href();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see org.xtext.example.mydsl.myDsl.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Selector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Selector#getName()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Selector#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.example.mydsl.myDsl.Selector#getTitle()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Title();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Selector#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see org.xtext.example.mydsl.myDsl.Selector#getOptions()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getName()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Link#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getDescription()
   * @see #getLink()
   * @generated
   */
  EReference getLink_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getUrl()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Menu <em>Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Menu</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu
   * @generated
   */
  EClass getMenu();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Menu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu#getName()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Menu#getMeal <em>Meal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Meal</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu#getMeal()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Meal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Menu#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu#getDescription()
   * @see #getMenu()
   * @generated
   */
  EReference getMenu_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Menu#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu#getPrice()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Price();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Menu#getImage <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image</em>'.
   * @see org.xtext.example.mydsl.myDsl.Menu#getImage()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Image();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MensamodelImpl <em>Mensamodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MensamodelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMensamodel()
     * @generated
     */
    EClass MENSAMODEL = eINSTANCE.getMensamodel();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENSAMODEL__HEADER = eINSTANCE.getMensamodel_Header();

    /**
     * The meta object literal for the '<em><b>Sidebar</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENSAMODEL__SIDEBAR = eINSTANCE.getMensamodel_Sidebar();

    /**
     * The meta object literal for the '<em><b>Footer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENSAMODEL__FOOTER = eINSTANCE.getMensamodel_Footer();

    /**
     * The meta object literal for the '<em><b>Menus</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENSAMODEL__MENUS = eINSTANCE.getMensamodel_Menus();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.HeaderImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__NAME = eINSTANCE.getHeader_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__DESCRIPTION = eINSTANCE.getHeader_Description();

    /**
     * The meta object literal for the '<em><b>Nav</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__NAV = eINSTANCE.getHeader_Nav();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SidebarImpl <em>Sidebar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SidebarImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSidebar()
     * @generated
     */
    EClass SIDEBAR = eINSTANCE.getSidebar();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIDEBAR__NAME = eINSTANCE.getSidebar_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIDEBAR__DESCRIPTION = eINSTANCE.getSidebar_Description();

    /**
     * The meta object literal for the '<em><b>Radio</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIDEBAR__RADIO = eINSTANCE.getSidebar_Radio();

    /**
     * The meta object literal for the '<em><b>Checkbox</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIDEBAR__CHECKBOX = eINSTANCE.getSidebar_Checkbox();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIDEBAR__SELECTOR = eINSTANCE.getSidebar_Selector();

    /**
     * The meta object literal for the '<em><b>Button</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIDEBAR__BUTTON = eINSTANCE.getSidebar_Button();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FooterImpl <em>Footer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FooterImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFooter()
     * @generated
     */
    EClass FOOTER = eINSTANCE.getFooter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOOTER__NAME = eINSTANCE.getFooter_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOOTER__DESCRIPTION = eINSTANCE.getFooter_Description();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOOTER__LINKS = eINSTANCE.getFooter_Links();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DescriptionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__NAME = eINSTANCE.getDescription_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NAVImpl <em>NAV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NAVImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNAV()
     * @generated
     */
    EClass NAV = eINSTANCE.getNAV();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAV__NAME = eINSTANCE.getNAV_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAV__DESCRIPTION = eINSTANCE.getNAV_Description();

    /**
     * The meta object literal for the '<em><b>Href</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAV__HREF = eINSTANCE.getNAV_Href();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RadioImpl <em>Radio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RadioImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRadio()
     * @generated
     */
    EClass RADIO = eINSTANCE.getRadio();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIO__NAME = eINSTANCE.getRadio_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RADIO__TITLE = eINSTANCE.getRadio_Title();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIO__OPTIONS = eINSTANCE.getRadio_Options();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckboxImpl <em>Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CheckboxImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckbox()
     * @generated
     */
    EClass CHECKBOX = eINSTANCE.getCheckbox();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__NAME = eINSTANCE.getCheckbox_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKBOX__TITLE = eINSTANCE.getCheckbox_Title();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__OPTIONS = eINSTANCE.getCheckbox_Options();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ButtonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__NAME = eINSTANCE.getButton_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__TITLE = eINSTANCE.getButton_Title();

    /**
     * The meta object literal for the '<em><b>Href</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__HREF = eINSTANCE.getButton_Href();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SelectorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__NAME = eINSTANCE.getSelector_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__TITLE = eINSTANCE.getSelector_Title();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__OPTIONS = eINSTANCE.getSelector_Options();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__NAME = eINSTANCE.getLink_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__DESCRIPTION = eINSTANCE.getLink_Description();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__URL = eINSTANCE.getLink_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MenuImpl <em>Menu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MenuImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMenu()
     * @generated
     */
    EClass MENU = eINSTANCE.getMenu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__NAME = eINSTANCE.getMenu_Name();

    /**
     * The meta object literal for the '<em><b>Meal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__MEAL = eINSTANCE.getMenu_Meal();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENU__DESCRIPTION = eINSTANCE.getMenu_Description();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__PRICE = eINSTANCE.getMenu_Price();

    /**
     * The meta object literal for the '<em><b>Image</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__IMAGE = eINSTANCE.getMenu_Image();

  }

} //MyDslPackage
