grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Mensamodel:
	(elements+=Tag)*
;	
Tag:
	'tag' name=STRING '{'
		(id=Html_Id)?
		(class=Html_Class)?
		(content=Content)?
		(children+=Children)*
	'}'	
;
Html_Id:
	'id' name=ID
;
Html_Class:
	'class' name=STRING
;
Content:
	'content' name=STRING
;
Children:
	'children' name=STRING '{'
		tags+=Tag
	'}'
;
	

	

